### ISSUE TITLE
一些css

### ISSUE THREAD

**Issue by Zhongyi-Li** [Zhongyi-Li/Blog#3]
1.box-shadow 实现0.5像素边框
```css
box-shadow:inset 0px -0.5px 0px 0px rgba(234,234,234,1)
```
2.箭头旋转动画
```css 
.arrow-up{
            transition: transform 0.3s;
            transform: rotateZ(180);
        }
 .arrow-down{
          transition: transform 0.3s;
          transform: rotateZ(0);
       }
```
